create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  role text not null check (role in ('admin', 'user'))
);

alter table public.tickets
  add column if not exists owner_user_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tickets_owner_user_id_fkey'
  ) then
    alter table public.tickets
      add constraint tickets_owner_user_id_fkey
      foreign key (owner_user_id) references public.app_users(id) on delete set null;
  end if;
end $$;

insert into public.app_users (username, password, role)
select 'admin', 'admin', 'admin'
where not exists (select 1 from public.app_users where lower(username) = 'admin');

insert into public.app_users (username, password, role)
select 'user', 'user', 'user'
where not exists (select 1 from public.app_users where lower(username) = 'user');

update public.tickets
set owner_user_id = (
  select id
  from public.app_users
  where lower(username) = 'admin'
  limit 1
)
where owner_user_id is null;
